### ISSUE TITLE
AAMAS Bidding Data

### ISSUE THREAD

**Issue by nmattei** [PrefLib/PrefLib-Contrib#1]
Ulle Endriss has provided the anonymized bidding data for AAMAS 2021. We need to set this data and add it to the existing entry.

Anonymised Bidding Data for AAMAS-2021
--------------------------------------

Ulle Endriss, May 2021 

The file aamas2021bidding.csv includes the anonymised bidding data collected for the 20th International Conference on Autonomous Agents and Multiagent Systems (AAMAS-2021).

The conference received 609 submissions that were both (i) reviewed by the programme committee and (ii) not withdrawn by the authors before the notification date. For 83 of these submissions the authors opted out of having the bidding data pertaining to their own submission included in this dataset.

The conference had 71 SPC members and 598 regular PC members, with 2 regular PC members opting out of having their bids included in this dataset.

This leaves 526 submissions, 71 SPC members, and 596 regular PC members. We randomly shuffled the submissions and then renamed them from 1 to 526. We did the same for S/PC members and renamed them from spc-1 to spc-71 and from pc-1 to pc-596, respectively.

Every S/PC member, for every submission, had the option to either declare a conflict or to bid 'yes', 'maybe', or 'no'. The default was 'no', and the 'no' bids have been omitted from the dataset.

Regular PC members were told that they would have to review at most 6 papers each (in the end they each had to review between 2 and 5 papers). The advice they were given was to bid positively ('yes' or 'maybe') on at least 40 papers. Note that the average number of positive bids actually received was much lower than that.

SPC members were told that they would have to handle at most 15 papers each (in the end they each had to handle between 8 and 9 papers). The advice they were given was to bid positively ('yes' or 'maybe') on at least 60 papers. Note that the average number of positive bids actually received was much lower than that.
[aamas2021bidding.csv](https://github.com/PrefLib/contribution/files/6657233/aamas2021bidding.csv)

**Comment by Simon-Rey** [comment]
Done

**Comment by Simon-Rey** [comment]
https://www.preflib.org/dataset/00037
