### ISSUE TITLE
Breakfast data

### ISSUE THREAD

**Issue by DominikPeters** [PrefLib/PrefLib-Contrib#14]
Name: Breakfast Items

Abbreviation: breakfast

Category: ED

Series Number: 00035

Path: ED/breakfast

Description: <p>This dataset was collected by Green and Rao (1972), and is a standard example in the literature on multidimensional unfolding (which is about embedding preferences in Euclidean space). They obtained strict preference rankings over a collection of 15 sweet breakfast items (such as toast, muffins, donuts) from "a group of 42 respondents, 21 Wharton MBA students and their wives. The questionnaire was self-administered separately by husband and wife. All subjects independently filled out the same questionnaire and received compensation for their efforts."</p><p>Green and Rao asked for these preferences in 6 different situations: "Overall preferences", "When I'm having a breakfast consisting of juice, bacon and eggs, and beverage", "When I'm having a breakfast consisting of juice, cold cereal, and beverage", "When I'm having a breakfast consisting of juice, pancakes, sausage, and beverage", "Breakfast, with beverage only", "At snack time, with beverage only". The rankings for each of these situations are provided in separate data patches. The ordering of respondents is the same across data patches; rankings in odd positions (1st, 3rd, ...) come from the MBA students, the ranking in the following line from that student's wife.</p><p>This dataset was digitized by <a href="https://dominik-peters.de">Dominik Peters</a> from the listings provided in the appendix of the <a href="https://archive.org/details/appliedmultidime0000unse/">1972 book</a>.</p>

Required Citations: Applied Multidimensional Scaling: A Comparison of Approaches and Algorithms; Paul E. Green, Vithala R. Rao; Holt, Rinehart and Winston; 1972

Selected Studies: 

description, status, file_name
Overall preference, original, ED-00035-00000001.soc
Juice, bacon and eggs, beverage, original, ED-00035-00000002.soc
Juice, cold cereal, beverage, original, ED-00035-00000003.soc
Juice, pancakes, sausage, beverage, original, ED-00035-00000004.soc
Breakfast, with beverage only, original, ED-00035-00000005.soc
At snack time, with beverage only, original, ED-00035-00000006.soc

[breakfast.zip](https://github.com/PrefLib/contribution/files/9228850/breakfast.zip)

**Comment by Simon-Rey** [comment]
Note that the dataset has been added to the PrefLib-Data github, it will be distributed after the next update of the website.

**Comment by DominikPeters** [comment]
Thanks Simon!

**Comment by Simon-Rey** [comment]
Quick questions:

- For 00035-00000004.soc, the orders at lines 50 and 51 of the file in your zip are the same. Based on the number of voters announced (42 with 41 unique orders), I deduce that the multiplicity should be 2 here and one of the lines deleted. Is it correct?

- Same for 00035-00000005.soc with the same lines 50 and 51.

**Comment by DominikPeters** [comment]
Ah, I may have misunderstood the specification of PrefLib files. In this dataset, the ordering of the voters matters (e.g. line 40 is the same person in all six files, and each even numbered line corresponds to a man with the next line his wife). So there should be no multiplicities and deletions. The 41 was merely the count of how many different orders there are, this could also be 42.

**Comment by Simon-Rey** [comment]
I see, the problem being that the parser fails on these files because the standard is that duplicated orders should not appear (since we have the multiplicity). Also, I cannot guarantee that the line ordering will be preserved over time ^^

**Comment by Simon-Rey** [comment]
Ok I solved the problem by adding a csv with the data across the files. That way someone interested by this fact will be able to use it, and the parser will be happy.

**Comment by Simon-Rey** [comment]
It's live!
