### ISSUE TITLE
Add Polkadot Data set

### ISSUE THREAD

**Issue by nmattei** [PrefLib/PrefLib-Contrib#18]
add from Nicolas Baumer -- 

Here’s some real world approval based committee votes (from blockchain elections) that could be usefully added to PrefLib …

 

Dataset

https://github.com/n-boehmer/ABC-practice-Polkadot

 

Paper about data set

https://arxiv.org/pdf/2312.11408.pdf

**Comment by Simon-Rey** [comment]
Done
