### ISSUE TITLE
Fix Preflib ED-00019: Oakland Election Data

### ISSUE THREAD

**Issue by nmattei** [PrefLib/PrefLib-Contrib#5]
We just noticed a small error in ED-00019: Oakland Election Data. The following elections are listed as 2010 but they were actually in 2012:

2010 Oakland City Council - At Large
M2010 Oakland City Council - District 1
2010 Oakland City Council - District 3
2010 Oakland City Council - District 5
2010 Oakland School Director - District 3

See https://www.acgov.org/rov/rcv/results/2012.htm. For example, here is the report for the District 1 election:

https://www.acgov.org/rov/rcv/results/rcvresults_6464.htm

Initially we got confused about why we couldn’t find the city council elections in official Alameda County records.

**Comment by Simon-Rey** [comment]
Corrected.
